name: ci
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      BATON_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      BATON_ON_BEHALF_OF_USER_ID: ${{ secrets.ON_BEHALF_OF_USER_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-greenhouse
        run: go build ./cmd/baton-greenhouse
      - name: Sync test
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-greenhouse
          baton-entitlement: 'role:site_admin:assigned'
          baton-principal: '4485008007'
          baton-principal-type: 'user'
